version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files for project"
    cmds:
      - protoc -I proto proto/authService/*.proto --go_out=gen/go/ --go_out=paths=source_relative --go-grpc_out=gen/go/ --go_out=paths=source_relative